## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [54]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [55]:
# Ваш код
a1 = np.zeros(5)
a2 = np.zeros((5, 1))
a3 = np.zeros((10, 2))
a4 = np.zeros((3, 6, 2))
a5 = np.zeros((4, 3, 2, 1))

Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [56]:
# Ваш код
b1 = np.ones(5, dtype=int)
b2 = np.ones((5, 1), dtype=int)
b3 = np.ones((10, 2), dtype=int)
b4 = np.ones((3, 6, 2), dtype=int)
b5 = np.ones((4, 3, 2, 1), dtype=int)

Задание 3.

Выполните для векторов выше `reshape` в
* 2 произвольных компоненты
* 3 произвольных компоненты
* 4 произвольных компоненты

In [57]:
# Ваш код
a1.reshape((5, 1))
a1.reshape((5, 1, 1))
b1.reshape((1, 1, 1, 5))
b2.reshape((1, 5))
a2.reshape((5, 1, 1))
b2.reshape((1, 1, 1, 5))
a3.reshape((4, 5))
a3.reshape((1, 5, 4))
b3.reshape((1, 1, 10, 2))
a4.reshape((2, 18))
a4.reshape((2, 6, 3))
b4.reshape((1, 3, 3, 4))
a5.reshape((12, 2))
b5.reshape((1, 4, 6))
b5.reshape((1, 2, 3, 4))

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]])

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [58]:
v = np.random.randint(0, 9, size=(5, 7))
v

array([[4, 7, 6, 1, 6, 0, 1],
       [1, 1, 7, 0, 5, 3, 3],
       [7, 1, 4, 5, 6, 3, 0],
       [7, 1, 2, 3, 8, 1, 6],
       [8, 5, 8, 6, 0, 1, 4]])

In [59]:
# Ваш код
max_ax1 = np.max(v, axis=1)
min_ax0 = np.min(v, axis=0)
sum_of_all = np.sum(v)
mean_ax0 = np.mean(v, axis=0)
median_ax1 = np.median(v, axis=1)
print(max_ax1)
print(min_ax0)
print(sum_of_all)
print(mean_ax0)
print(median_ax1)

[7 7 7 8 8]
[1 1 2 0 0 0 0]
131
[5.4 3.  5.4 3.  5.  1.6 2.8]
[4. 3. 4. 3. 5.]


Задание 6.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [60]:
# Ваш код
v_shape = v.shape
print(v_shape)
print(v_shape[0])
print(v_shape[1])

(5, 7)
5
7


Задание 7.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Отсортированный список индексов

In [61]:
# Ваш код
print(v[v > 5])
print(v[v < 7][::-1])
print(v[(v > 3) & (v % 4 == 0)])
print(v[v % 5 == 3])
print(np.argmax(v))
print(np.argmin(v))
print(np.argsort(v))

[7 6 6 7 7 6 7 8 6 8 8 6]
[4 1 0 6 5 6 1 3 2 1 0 3 6 5 4 1 3 3 5 0 1 1 1 0 6 1 6 4]
[4 4 8 8 8 4]
[3 3 3 3 8 8 8]
25
5
[[5 3 6 0 2 4 1]
 [3 0 1 5 6 4 2]
 [6 1 5 2 3 4 0]
 [1 5 2 3 6 0 4]
 [4 5 6 1 3 0 2]]


Задание 8.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [62]:
# Ваш код
print(v * 3)
print(v / 7)
print(v ** (2/3))
print(np.sin(v))
print(np.log1p(v))

[[12 21 18  3 18  0  3]
 [ 3  3 21  0 15  9  9]
 [21  3 12 15 18  9  0]
 [21  3  6  9 24  3 18]
 [24 15 24 18  0  3 12]]
[[0.57142857 1.         0.85714286 0.14285714 0.85714286 0.
  0.14285714]
 [0.14285714 0.14285714 1.         0.         0.71428571 0.42857143
  0.42857143]
 [1.         0.14285714 0.57142857 0.71428571 0.85714286 0.42857143
  0.        ]
 [1.         0.14285714 0.28571429 0.42857143 1.14285714 0.14285714
  0.85714286]
 [1.14285714 0.71428571 1.14285714 0.85714286 0.         0.14285714
  0.57142857]]
[[2.5198421  3.65930571 3.30192725 1.         3.30192725 0.
  1.        ]
 [1.         1.         3.65930571 0.         2.92401774 2.08008382
  2.08008382]
 [3.65930571 1.         2.5198421  2.92401774 3.30192725 2.08008382
  0.        ]
 [3.65930571 1.         1.58740105 2.08008382 4.         1.
  3.30192725]
 [4.         2.92401774 4.         3.30192725 0.         1.
  2.5198421 ]]
[[-0.7568025   0.6569866  -0.2794155   0.84147098 -0.2794155   0.
   0.84147098]
 [ 0.841

### Разные инициализации + индексирование (3 балла)

Задание 9.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [63]:
# Ваш код
print(np.arange(1,18, 2).reshape((3, 3)))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Задание 10.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [64]:
# Ваш код
print(np.arange(-16, 15, 2)[::-1].reshape(4,4))

[[ 14  12  10   8]
 [  6   4   2   0]
 [ -2  -4  -6  -8]
 [-10 -12 -14 -16]]


Задание 11.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [65]:
x = [-0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5] # красивый вариант
#x = np.arange(-0.5, 0.6, 0.1) # некрасивый вариант
grid = np.zeros((11,11), [('x', float),('y', float)])
grid['x'], grid['y'] = np.meshgrid(x, x[::-1])
grid
# не до конца понял, как сделать, чтобы ровно 11 tupl'ов было на 1 строчке

array([[(-0.5,  0.5), (-0.4,  0.5), (-0.3,  0.5), (-0.2,  0.5),
        (-0.1,  0.5), ( 0. ,  0.5), ( 0.1,  0.5), ( 0.2,  0.5),
        ( 0.3,  0.5), ( 0.4,  0.5), ( 0.5,  0.5)],
       [(-0.5,  0.4), (-0.4,  0.4), (-0.3,  0.4), (-0.2,  0.4),
        (-0.1,  0.4), ( 0. ,  0.4), ( 0.1,  0.4), ( 0.2,  0.4),
        ( 0.3,  0.4), ( 0.4,  0.4), ( 0.5,  0.4)],
       [(-0.5,  0.3), (-0.4,  0.3), (-0.3,  0.3), (-0.2,  0.3),
        (-0.1,  0.3), ( 0. ,  0.3), ( 0.1,  0.3), ( 0.2,  0.3),
        ( 0.3,  0.3), ( 0.4,  0.3), ( 0.5,  0.3)],
       [(-0.5,  0.2), (-0.4,  0.2), (-0.3,  0.2), (-0.2,  0.2),
        (-0.1,  0.2), ( 0. ,  0.2), ( 0.1,  0.2), ( 0.2,  0.2),
        ( 0.3,  0.2), ( 0.4,  0.2), ( 0.5,  0.2)],
       [(-0.5,  0.1), (-0.4,  0.1), (-0.3,  0.1), (-0.2,  0.1),
        (-0.1,  0.1), ( 0. ,  0.1), ( 0.1,  0.1), ( 0.2,  0.1),
        ( 0.3,  0.1), ( 0.4,  0.1), ( 0.5,  0.1)],
       [(-0.5,  0. ), (-0.4,  0. ), (-0.3,  0. ), (-0.2,  0. ),
        (-0.1,  0. ), ( 0. ,  0. ), ( 0.1

Задание 12.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [66]:
# Ваш код
chess_grid = np.zeros((8,8), dtype=int)
chess_grid[::2, ::2] = 1
chess_grid[1::2, 1::2] = 1
print(chess_grid)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание 13.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [67]:
# Ваш код
mask = np.logical_not(chess_grid == 0)
chess_grid[np.logical_not(chess_grid == 1)] = 1
chess_grid[mask] = 0
chess_grid
# можно было просто и проще :
# chess_grid[1::2, 1::2] = 1
# chess_grid[::2, ::2] = 1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Задание 14.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [68]:
# Ваш код i < j - условние нижнетреугольности
def create_lower_triangular_matrix(size=3):
    M = np.ones((size, size), dtype=int)
    M[np.triu_indices(size, k=1)] = 0
    return M

print(create_lower_triangular_matrix(5))

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


Задание 15.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [69]:
# Ваш код
def create_upper_triangular_matrix(size=3):
    M = np.ones((size, size), dtype=int)
    M[np.tril_indices(size, k=-1)] = 0
    return M

print(create_upper_triangular_matrix(5))

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


Задание 16.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [70]:
# Ваш код
def matrix(size=3):
    M = np.eye(size, dtype=int)
    return np.fliplr(M)
print(matrix(4))

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]


### Операции + аггрегации (3 балла)

Задание 17.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [71]:
def expected_value(x):
    return sum(x) / len(x)


def dispersion(x):
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [72]:
def expected_value_np(x):
    return np.mean(x)

In [73]:
def dispersion_np(x):
    return np.var(x)

In [74]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [75]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [76]:
def mean_square_difference_np(y1, y2):
    return ((y1 - y2).T).dot((y1 - y2)) / y1.shape[0]

In [77]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [78]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2)
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [79]:
def mean_abs_difference_np(y1, y2):
    return np.sum(np.abs(y1 - y2)) / y1.shape[0]

In [80]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 20.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [81]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2)
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [82]:
def matching_proba_np(y1, y2):
    return np.sum(y1 == y2) / y1.shape[0]

In [83]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 21.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

* Необходимо найти границы (индексы), такие, что если мы разделим какой-то из них все два вектора, то в левой части пересекающихся в $y_1$ и $y_2$ нулей будет больше, чем единиц, а в правой - наоборот

In [84]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    print("Matching zeros:", matching_zeros)
    print("Matching ones:", matching_ones)
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [85]:
def find_thresholds_np(y1, y2):
    result = []
    matching_zeros = (y2 == 0)&(y1 == 0)
    matching_ones = (y2 == 1)&(y1 == 1)

    percent_of_zeros_on_the_left_of_index = np.cumsum(matching_zeros)[:-1] / np.arange(1, y1.shape[0])
    percent_of_ones_on_the_right_of_index = (
        (np.cumsum((matching_ones)[::-1])[::-1])[:-1] / np.arange(1, y1.shape[0])[::-1]
    )
    if np.sum(matching_ones) / y1.shape[0] > 0.5:
        result.append(0)
    result = np.array(result, dtype=int)
    mask = (percent_of_zeros_on_the_left_of_index > 0.5)&(percent_of_ones_on_the_right_of_index > 0.5)
    mid_indices = np.arange(1, y1.shape[0])[mask]
    
    result = np.concatenate((result, mid_indices))
    if np.sum(matching_zeros) / y1.shape[0] > 0.5:
        result = np.concatenate((result, [y1.shape[0]]))
    return result


In [86]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

Matching zeros: [1]
Matching ones: [0]
Matching zeros: [0]
Matching ones: [1]
Matching zeros: [1, 1, 0, 0]
Matching ones: [0, 0, 1, 1]
Matching zeros: [1, 1, 0, 1, 1, 0, 0, 0]
Matching ones: [0, 0, 0, 0, 0, 1, 1, 1]


### Разные действия с матрицами (3 балла)

Задание 22.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно пяти** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [87]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))

# (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

#data = data.sum(axis=1).sum(axis=2).sum(axis=1).reshape((32, 1))
### так можно? или использовать исключительно stack/concatenate?

data = data.reshape((3, 32, 16, 16))
data = np.concatenate((data[0], data[1], data[2]), axis=0).reshape((2, 16, 768))
data = np.concatenate((data[0], data[1]), axis=0)
data = np.sum(data, axis=1).reshape((32, 1))
#можно еще так: data = data[:, 0].reshape((32, 1))
# Преобразование 2
# Преобразование 3
# Преобразование 4
# Преобразование 5

assert data.shape == (32, 1)

Задание 23.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [88]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

# (∩｀-´)⊃━☆ﾟ.*･｡ﾟ !!!magic!!!
m1.resize((16, 512))
W1.resize((16, 512))
W2.resize((16, 512))
W1 = W1 + W2
m1 = np.hstack((m1, W1))
m1.resize((512, 32))
result = m2.dot(m1)

assert result.shape == (32, 32)

Задание 24.

Последнее испытание для юного мага матриц - приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [89]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

test = np.hsplit(result, [9, 20])
test = list(map(lambda arr : np.sum(arr, axis=1) / np.sum(arr), test))
result = np.vstack((test[0], test[1], test[2])) # можно ли так делать?...
result.reshape(32, 3)

assert ((result >= 0) & (result <= 1)).all()